name: Mirror to Codeberg

on:
  push:
    branches:
      - master

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Codeberg
        run: |
          git remote add codeberg https://kikikian:${{ secrets.CODEBERG_TOKEN }}@codeberg.org/kikikian/transfer.git
          git push codeberg master --force
